//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RASBOGTR\\SQLEXPRESS;Initial Catalog=QL_CUAHANG;User ID=sa;Pass" +
            "word=sa2014")]
        public string QL_CUAHANGConnectionString {
            get {
                return ((string)(this["QL_CUAHANGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RASBOGTR;Initial Catalog=PHANMEM_CHTIENLOI;User ID=sa;Password" +
            "=sa2014")]
        public string PHANMEM_CHTIENLOIConnectionString {
            get {
                return ((string)(this["PHANMEM_CHTIENLOIConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RASBOGTR;Initial Catalog=DA_CNPM;User ID=sa;Password=sa2014")]
        public string DA_CNPMConnectionString {
            get {
                return ((string)(this["DA_CNPMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-NTU0LN1\\SQLEXPRESS;Initial Catalog=DA_CNPM;User ID=sa;Passwor" +
            "d=123")]
        public string DA_CNPMConnectionString1 {
            get {
                return ((string)(this["DA_CNPMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RASBOGTR;Initial Catalog=DA_CNPM_Master;User ID=sa;Password=sa" +
            "2014")]
        public string DA_CNPM_MasterConnectionString {
            get {
                return ((string)(this["DA_CNPM_MasterConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-RASBOGTR;Initial Catalog=DA_CNPM_FINAL;User ID=sa;Password=sa2" +
            "014")]
        public string DA_CNPM_FINALConnectionString {
            get {
                return ((string)(this["DA_CNPM_FINALConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI;Initial Catalog=DA_CNPM_FINAL;Persist Security Info=True;User ID=" +
            "sa;Password=123")]
        public string DA_CNPM_FINALConnectionString1 {
            get {
                return ((string)(this["DA_CNPM_FINALConnectionString1"]));
            }
        }
    }
}
